Repository ChromeGaming/Community-Page, pull requests merged in 2024-07, with the labels that each got.

#359 Rate us page is added
  public/css/styles.css
  public/js/script.js
  server/views/about.ejs
  server/views/index.ejs
  server/views/partials/rateus.ejs
  server/views/play.ejs
  server/views/playgames.ejs
  server/views/products.ejs
Labels: gssoc, level2

#357 Added Social Media links
  public/css/styles.css
  public/images/envelope.png
  server/views/about.ejs
  server/views/index.ejs
  server/views/play.ejs
  server/views/products.ejs
Labels: gssoc, level2

#356 make changes in readme #352
  README.md
Labels: gssoc, level1

#353 fixed responsiveness of about section
  public/css/styles.css
  server/views/about.ejs
Labels: gssoc, level2

#355 Button hoverings
  public/css/styles.css
  server/views/products.ejs
Labels: gssoc, level2, Under Review

#374 fixed
  server/views/about.ejs
  server/views/products.ejs
Labels: gssoc, level1

#372 changed_icons_color
  server/views/index.ejs
Labels: gssoc, level1

#371 added 'X' icon
  public/css/styles.css
Labels: gssoc, level1

#378 Pre loader
  public/images/loader.gif
  server/views/index.ejs
Labels: gssoc, level2

#373 Update script.js
  public/js/script.js
Labels: gssoc, level2, Need changes

#400 Navbar links are now visible in every mode .
  server/views/index.ejs
Labels: gssoc, level1

#394 fixed issue #381
  .idea/.gitignore
  .idea/Community-Page.iml
  .idea/material_theme_project_new.xml
  .idea/modules.xml
  .idea/vcs.xml
  public/css/styles.css
Labels: gssoc, level2

#404 Issue 386
  .idea/workspace.xml
  public/js/script.js
  server/views/about.ejs
  server/views/index.ejs
  server/views/play.ejs
  server/views/products.ejs
Labels: gssoc, level2

#408 fixed issue 385
  public/css/styles.css
  server/views/index.ejs
Labels: gssoc, level1

#405 fixed issue 390
  server/views/index.ejs
Labels: gssoc, level1

#402 Fix Rate Us Page Appearance Issue in Light Mode
  public/css/styles.css
Labels: gssoc, level2

#401 Add images of contributors in leaderboard
  public/css/styles.css
  public/js/script.js
  server/package-lock.json
Labels: gssoc, level2

#409 Added hover effect
  public/css/styles.css
  public/js/script.js
Labels: gssoc, level1, Under Review

#406 fixed issue 389
  .idea/inspectionProfiles/Project_Default.xml
  public/css/styles.css
Labels: gssoc, level1
