Repository ChromeGaming/Community-Page, pull requests merged in 2024-05, with the labels that each got.

#31 fixed issue #3
  index.html
  styles.css
Labels: GSSoC'24, Level - 1, Approved

#33 fixed discord btn issue #2
  script.js
Labels: GSSoC'24, Level - 2, Approved

#38 fixed issue #4
  index.html
Labels: GSSoC'24, Level - 1, Approved

#43 Added Hover effect on social media icons
  styles.css
Labels: GSSoC'24, Level - 1, Approved

#57 Bug Fix + Feature Add in Subscribe Field issue #47
  index.html
  script.js
  styles.css
Labels: GSSoC'24, Level - 2, Approved

#62 [Feature] : Search result added
  index.html
  package-lock.json
  script.js
  styles.css
Labels: GSSoC'24, Level - 2, Approved

#67 Added about page
  about.html
  styles.css
Labels: GSSoC'24, Level - 2, Approved

#72 Added a customised scroll bar
  styles.css
Labels: GSSoC'24, Level - 2, Approved

#22 Added hover effect to navbar
  index.html
  script.js
  styles.css
Labels: GSSoC'24, Level - 2, Approved

#69 Progress icon
  index.html
  medal.png
  styles.css
Labels: GSSoC'24, Level - 2, Approved

#73 Faq section
  .vscode/settings.json
  index.html
  script.js
  styles.css
Labels: gssoc, level2

#91 routing added
  about.html
  index.html
Labels: gssoc, level1, Approved

#144 added favicons to each and every page , also connecting them through hyperlinks.
  about.html
  contribute.html
  favicon.PNG
  index.html
  logo.PNG
  playgames.html
  products.html
  styles.css
Labels: Under Review

#86 [New Feature]: Improvement of social link to share button view . Assign under GSSOC'24
  close.svg
  index.html
  script.js
  styles.css
Labels: gssoc, level2, Need Change

#115 [New Feature]: SearchBar Some changes for search Related
  index.html
  script.js
  styles.css
Labels: gssoc, level2, Approved

#141 Space added in Fauget.gif.
  index.html
Labels: gssoc, level1, Approved

#162 Gif on Homepage changed Successfully
  index.html
  logo.gif
  styles.css
Labels: gssoc, level2, Approved

#137 Fixes #129
  .github/workflows/autocomment-pr-raise.yml
Labels: gssoc, level2, Approved

#138 Fixes #127
  .github/workflows/autocomment-issue.yml
Labels: gssoc, level2, Approved

#167 Successfully Created the Timeline in the about page
  about.html
  styles.css
Labels: gssoc, level2

#172 Adding leaderboard using api as said in issue #170
  index.html
  script.js
Labels: enhancement, gssoc, level2, Approved

#178 [Bug]: Responsive Search bar
  styles.css
Labels: gssoc, level2, Approved

#136 feat: Added scroll to top feature button
  index.html
  script.js
  styles.css
Labels: gssoc, level2, Approved

#212 Fixed the navigation behavior of footer tabs! #175
  index.html
Labels: bug, gssoc, level1

#214 "Join Now" Text Visible
  index.html
Labels: gssoc, level1, Need changes

#215 Added Light and dark mode feature in Product page and fixed some visibility issues and broken links
  about.html
  contribute.html
  index.html
  play.html
  playgames.html
  product.html
  products.html
Labels: bug, gssoc, level1

#217 changed the gif's on all the pages
  Fauget.gif
  about.html
  contribute.html
  play.html
  product.html
  styles.css
Labels: bug, gssoc, level2

#220 Website theme persists through reload
  script.js
Labels: bug, gssoc, level1

#166 Solved issue #101- Headings like Legal, Info, Explore, etc are not visible
  about.html
Labels: gssoc, level2, Approved

#234 changes the navbar and changed the links to products page everywhere
  about.html
  contribute.html
  index.html
  play.html
  playgames.html
  products.html
Labels: bug, enhancement, gssoc, level1

#258 Fixed navbar
  public/css/styles.css
Labels: gssoc, level1, Approved

#259 hover effect added to footer and bug fixed
  server/package-lock.json
  server/package.json
  server/views/index.ejs
Labels: gssoc, level1

#213 solve discord button that text color changed in light mode to white c…
  index.html
  server/views/index.ejs
Labels: gssoc, level2

#265 Added footer section in product , play games ,contribute
  server/views/contribute.ejs
  server/views/play.ejs
Labels: gssoc, level2, Approved

#269 Responsive navbar
  server/views/about.ejs
  server/views/contribute.ejs
  server/views/play.ejs
  server/views/playgames.ejs
  server/views/products.ejs
Labels: gssoc, level2, Approved
