Repository ChromeGaming/Community-Page, pull requests merged in 2024-06, with the labels that each got.

#270 Button Style and Navbar Overlapping issue Solved
  public/css/styles.css
  server/views/play.ejs
  server/views/playgames.ejs
Labels: gssoc, level2, Approved

#271 enhanced the visibility of text in all modes
  public/css/styles.css
  server/views/about.ejs
Labels: gssoc, level2, Approved

#275 [Documentation Bug]: Would like to add Contributors logo's to Readme.…
  README.md
Labels: documentation, gssoc, level1

#268 UI Enhanced - Navbar
  server/views/index.ejs
Labels: gssoc, level2

#292 [Docs]: Create Learn.md File
  Learn.md
Labels: gssoc, level2

#283 Added the page logo to all pages #246
  server/views/about.ejs
  server/views/contribute.ejs
  server/views/index.ejs
  server/views/play.ejs
  server/views/playgames.ejs
  server/views/products.ejs
Labels: gssoc, level2

#286 Navbar Content Style Update
  index.html
  public/css/styles.css
Labels: gssoc, level2, Under Review

#288 Social media toggler added
  public/css/styles.css
  public/images/social1.webp
  public/js/script.js
  server/views/about.ejs
  server/views/contribute.ejs
  server/views/index.ejs
  server/views/play.ejs
Labels: gssoc, level2

#280 Improved the responsiveness
  public/css/styles.css
  server/views/about.ejs
  server/views/contribute.ejs
  server/views/index.ejs
  server/views/play.ejs
  server/views/playgames.ejs
  server/views/products.ejs
Labels: gssoc, level3

#306 Completes
  server/views/about.ejs
Labels: gssoc, level1

#316 Fixed alignment and styled headings of all pages
  public/css/styles.css
  server/views/about.ejs
  server/views/contribute.ejs
  server/views/index.ejs
  server/views/play.ejs
  server/views/products.ejs
Labels: gssoc, level1

#315 Implement Automatic Closure Feature for Old Issues
  .github/workflows/close-old-issue.yml
Labels: gssoc, level1

#327 Added animated cursor functionality
  public/css/styles.css
  server/views/about.ejs
  server/views/index.ejs
  server/views/play.ejs
  server/views/products.ejs
Labels: gssoc, level3, Need Change

#345 fixed menu in index file
  server/views/index.ejs
Labels: gssoc, level2

#349 added github avatar of each contributer annd their profile link dynamically
  public/css/styles.css
  server/views/index.ejs
Labels: gssoc, level3

#350 Active Pages
  public/css/styles.css
  server/views/about.ejs
  server/views/index.ejs
  server/views/play.ejs
  server/views/products.ejs
Labels: gssoc, level2
